lerna.json
package.json
packages/config.webpack/package.json
packages/core/package.json
packages/extension.webpack-babel/package.json
packages/extension.webpack-css/package.json
packages/extension.webpack-eslint/package.json
packages/preset.webpack-spa/package.json
packages/ts-config/package.json

chore(): fix package.json

---

README.md
packages/config.webpack/README.md
packages/config.webpack/src/WebpackConfig.ts
packages/core/README.md
packages/extension.webpack-babel/README.md
packages/extension.webpack-css/README.md
packages/extension.webpack-eslint/README.md
packages/preset.webpack-spa/README.md

| Fixed Issues?            | Fixes #6 

docs(): write readme for all packages

---

README.md
packages/core/README.md
packages/core/package.json

| Fixed Issues?            | 
Add core conceptions

docs(): improve readme

---

examples/react/package.json
ideas.txt
packages/core/src/AbstractExtension.ts
packages/core/src/AbstractPreset.ts
packages/extension.webpack-babel/README.md
packages/extension.webpack-babel/src/index.ts

| Fixed Issues?            | Fixes #24 
| Major: Breaking Change?  | +

feature(): improve read of options

---

packages/core/src/AbstractPreset.ts
packages/core/src/utils/getBaseClass.ts

| Fixed Issues?            | Closes #23 

feature(core): add logic to handle substitutability of extensions

---

examples/react/package.json
packages/extension.webpack-babel.react/LICENSE
packages/extension.webpack-babel.react/README.md
packages/extension.webpack-babel.react/package.json
packages/extension.webpack-babel.react/src/index.ts
packages/extension.webpack-babel.react/tsconfig.json

feature(extension.webpack-babel.react): create package

---

packages/preset.webpack-spa/bin/cli.js

| Fixed Issues?            | `Fixes #1, Fixes #2` 

improvement(preset.webpack-spa): handle unhandled rejections

---

.sail.yml
package.json
packages/config.webpack/package.json
packages/core/package.json
packages/extension.webpack-babel.react/package.json
packages/extension.webpack-babel/package.json
packages/extension.webpack-css/package.json
packages/extension.webpack-eslint/package.json
packages/preset.webpack-spa/package.json
packages/tsconfig.json

| Fixed Issues?            | Closes #28 

fix(): fix slow compilation by stopping use separated package building

---

README.md
packages/config.webpack/README.md
packages/config.webpack/package.json
packages/core/README.md
packages/core/package.json
packages/extension.webpack-babel.react/README.md
packages/extension.webpack-babel.react/package.json
packages/extension.webpack-babel/README.md
packages/extension.webpack-babel/package.json
packages/extension.webpack-css/README.md
packages/extension.webpack-css/package.json
packages/extension.webpack-eslint/README.md
packages/extension.webpack-eslint/package.json
packages/preset.webpack-spa/README.md

 docs(): great improve to readme, fix mistakes

---

COMPARISON.md
README.md
packages/config.webpack/README.md
packages/core/README.md
packages/extension.webpack-babel.react/README.md
packages/extension.webpack-babel.react/package.json
packages/extension.webpack-babel/README.md
packages/extension.webpack-babel/package.json
packages/extension.webpack-css/README.md
packages/extension.webpack-eslint/README.md
packages/extension.webpack-eslint/package.json
packages/preset.webpack-spa/README.md
packages/preset.webpack-spa/package.json

docs(readme): improve readme

---

packages/config.webpack/src/WebpackConfig.ts
packages/core/src/AbstractConfigBuilder.ts
packages/core/src/ConfigModification.ts

it's optionally and enables to avoid the repeat of modifications

feature(core): implement identification for modifications

---

packages/extension.webpack-css/src/index.ts
packages/extension.webpack-sass/src/index.ts
yarn.lock

fix(): prevent repeating modifications

---

packages/extension.webpack-babel/README.md
packages/extension.webpack-babel/src/index.ts

| Fixed Issues?            | Closes #45 

feature(extension.webpack-babel): add option for adding plugins

---

packages/core/src/AbstractPreset.ts
packages/core/src/decorators/ReadOptions.ts
packages/preset.webpack-spa/package.json
packages/preset.webpack-spa/src/WebpackPresetWeb.ts
packages/preset.webpack-spa/src/extensions/addCleanWebpackPlugin.ts
packages/preset.webpack-spa/src/extensions/addCopyWebpackPlugin.ts
packages/preset.webpack-spa/src/extensions/addFriendlyErrorsWebpackPlugin.ts
packages/preset.webpack-spa/src/extensions/index.ts
yarn.lock

| Fixed Issues?            | Closes #49 
+ remove debug console logs at core
+ fixes mistype namings

improvement(preset.webpack-spa): improve console logging

---

README.md
packages/config.webpack/README.md
packages/core/README.md
packages/extension.webpack-babel.react/README.md
packages/extension.webpack-sass/README.md

docs(): update readme

---

packages/config.webpack/package.json
packages/core/package.json
packages/extension.webpack-babel.react/package.json
packages/extension.webpack-babel/package.json
packages/extension.webpack-css/package.json
packages/extension.webpack-eslint/package.json
packages/extension.webpack-sass/package.json
packages/preset.webpack-spa/package.json
packages/utils.webpack-styles/package.json
yarn.lock

| Fixed Issues?            | Fixes #65 

chore(deps): update and lock dependencies

---

examples/react-typescript/package.json
packages/extension.webpack-eslint/README.md
packages/extension.webpack-eslint/package.json
packages/extension.webpack-eslint/src/index.ts
yarn.lock

feature(extension.webpack-eslint): TypeScript support; new options for customize

---

examples/react-typescript/package.json
examples/react/package.json
packages/config.webpack/src/index.ts
packages/extension.webpack-pwa/LICENSE
packages/extension.webpack-pwa/README.md
packages/extension.webpack-pwa/package.json
packages/extension.webpack-pwa/src/index.ts
packages/extension.webpack-pwa/tsconfig.json
packages/tsconfig.json
yarn.lock

| Fixed Issues?            | Closes #68 

extension.webpack-pwa: Create extension, which adds PWA capabilities

---

packages/config.webpack/src/WebpackConfig.ts
packages/extension.webpack-css/package.json
packages/extension.webpack-css/src/index.ts
packages/extension.webpack-sass/package.json
packages/extension.webpack-sass/src/index.ts
yarn.lock

`config.webpack`: New method in WebpackConfig to add minimizers

extension.webpack-{css,sass}: Add styles minification

---

packages/config.webpack/package.json
packages/config.webpack/src/createWebpackConfiguration.ts
packages/core/src/helpers/extensionsRegex.ts
yarn.lock

| Fixed Issues?            | 
There is no need write more
**index.js**
```js
if (module.hot) {
module.hot.accept();
}
```
Automatic HMR in-the-box

config.webpack: Add hot-accept-webpack-plugin

---

.sail.yml
jest.config.js
package.json

Stop running tests before commit (husky); build and test tasks now parallel

---

.cirrus.yml
package.json

Fix Cirrus CI

---

.cirrus.yml

| Fixed Issues?            | `Fixes #1, Fixes #2` 
This should fix it.

Update cirrus config

---

e2e-helpers/run.ts
e2e-helpers/waitForHttpStatus.ts
examples/__tests__/react-typescript.test.ts
examples/__tests__/react.test.ts
packages/core/src/utils/__tests__/extractFirstPropChain.test.ts
packages/core/src/utils/__tests__/getBaseClass.test.ts
packages/core/src/utils/__tests__/package.json
packages/core/src/utils/__tests__/readJson.test.ts
packages/core/src/utils/__tests__/readPackageJson.test.ts
packages/core/src/utils/readJson.ts
packages/core/src/utils/readPackageJson.ts
yarn.lock

Add caching and tests for readJson/readPackageJson

---

.eslintignore
e2e-helpers/run.ts
e2e-helpers/waitForHttpStatus.ts
examples/__tests__/react-typescript.test.ts
examples/__tests__/react.test.ts
examples/react-typescript/package.json
examples/react/package.json
package.json
packages/core/bin/run.js
packages/core/src/AbstractConfigBuilder.ts
packages/core/src/AbstractOptionsContainer.ts
packages/core/src/types/ExtractOptions.ts
packages/plugin-webpack-babel/package.json
packages/plugin-webpack-css/package.json
packages/plugin-webpack-eslint/package.json
packages/plugin-webpack-pwa/package.json
packages/plugin-webpack-pwa/src/WebpackPwaPlugin.ts
packages/plugin-webpack-react/package.json
packages/plugin-webpack-sass/package.json
packages/plugin-webpack-spa/package.json
packages/plugin-webpack-spa/src/WebpackSpaPlugin.ts
packages/utils-webpack-styles/package.json
packages/webpack-config/package.json
yarn.lock

Update npm dependencies and regenerate yarn.lock
Configure Eslint to handle examples/__tests__ folder

Improve e2e tests (simplify & fix some bugs)

---

examples/react-typescript/package.json
package.json
packages/plugin-webpack-spa/package.json
packages/plugin-webpack-spa/src/WebpackSpaPlugin.ts
packages/webpack-config/package.json
packages/webpack-config/src/createWebpackConfiguration.ts
yarn.lock

- Replace Fastify with Express

(plugin-webpack-spa) Upgrade webpack-dev-middleware to 4.0.0-rc.1
